version: '3.7'
services:
  php72:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php72
    ports:
      - 8080:80 
    depends_on:
      - postgres

  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=VAM
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5438:5432
    volumes:
      - ./postgres/data:/var/lib/postgres/data
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgres/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql